name: fyp
description: "A menstrual health app using for fyp project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  smooth_page_indicator: ^1.0.0+2

flutter:
  uses-material-design: true
  fonts:
    - family: HermeneusOne
      fonts:
        - asset: assets/fonts/HermeneusOne-Regular.ttf
  assets:
    - assets/images/
    - assets/icons/
    - assets/tileicons/
    - assets/how_work/
